apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-cortex
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/swisscom/provider-cortex
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A cortex that can be used to create Crossplane providers.
